### ISSUE TITLE
Spacing

### ISSUE THREAD

**Issue by kmgallahan** [opusman/ClockPositionRighteousifier#1]
Would it be possible to remove the extra spacing between the clock and Action Center icon? There appears to be something like 10px between them as visible when comparing the mouse-over visual states of both items.

**Comment by PARAdoxx7** [comment]
Seconded! Actually, the spacing does not stem from the ClockPositionRighteousifier – it is the standard spacing between the notification icon and what comes after it (normally the _Show Desktop_ button, as seen in the picture). This program swaps the clock and the notification icon, which relocates the said spacing together with the notification icon. If possible, it would be best to restore the spacing to the right, after the clock, for aesthetics.

Anyway, many thanks to the author of CPR :) 

![s3](https://cloud.githubusercontent.com/assets/20616676/19216781/a0b88ca2-8dca-11e6-8044-dc150364add4.jpg)

**Comment by Imold** [comment]
I to would like that spacing between the clock and the show desktop button.
